apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: uplane
  namespace: vran
spec:
  config: >-
    { "cniVersion": "0.3.1", "name": "testuplane", "type": "ipvlan", "master":
    "enp7s0", "mode": "l2", "ipam": {"type": "static","addresses": [{"address":
    "100.64.0.10/24"}] } }
